### ISSUE TITLE
Styles don't support CSS dark style

### ISSUE THREAD

**Issue by cassidyjames** [Huluti/TuxHomepage#13]
I came across this site and was bummed to see it didn't automatically use a dark style when the OS/browser requests it. You can support a dark style by providing separate styles for a `prefers-color-scheme: dark` CSS media query.

**Comment by Huluti** [comment]
It's funny that people keep watching this little project. It's been a long time since I made any change. I kept it more like an archive. 
I know prefers-color-scheme: dark, I'll try to add it soon. Thank's ;)  At the same time, I have been an eOS user for a while and I admire your work.
