### ISSUE TITLE
[Improvement]Change font to accomodate for more non-Latin languages

### ISSUE THREAD

**Issue by lmintmate** [Huluti/TuxHomepage#8]
I've written a Greek translation of your great webpage and, before I do the pull request, thought I'd check whether the font used  in the site is compatible with Greek. According to the index.html file, you're using PT Sans from Google fonts, which is only compatible with Russian, in regards to non-Latin text. I'd be grateful thus if you used instead a font (from Google Fonts ofc, if that makes your life easier) with compatibility for Greek as well (I personally have three in mind: Open Sans, Roboto and Noto Sans).
Thanks again.

**Comment by Huluti** [comment]
Done. Thank you! I'm waiting for your PR.
